apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-qa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/BE-BOUNCY-WWD/BB-INFRA.git
    targetRevision: main
    path: BB-INFRA/charts/microservices
    helm:
      valueFiles:
        - ../../environments/qa/values-microservices.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      labels:
        environment: qa
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
